project:
  type: website
  output-dir: docs

website:
  title: "Spetses Introductory Course"
  navbar:
    left:
      - href: index.qmd
        text: What is this?
      - Data_import_cleaning.qmd
      - Case_definition.qmd
      - Lab_and_Descriptive.qmd
      - Univariate.qmd
      - Stratified.qmd
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/EPIET/IntroCourse_inCop/tree/main
          - text: Report a code issue
            url:  https://github.com/EPIET/IntroCourse_inCop/issues

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: show
    code-summary: "Show the code"
    code-tools: true
    df-print: paged

editor: visual


