project:
  type: website
  pre-render: extract_code.R
  output-dir: docs

website:
  title: "Intro Course"
  navbar:
    left:
      - href: index.qmd
        text: What is this?
      - 01_Data_import_cleaning.qmd
      - 02_Case_definition.qmd
      - 03_Lab_and_Descriptive.qmd
      - 04_Univariable.qmd
      - 05_Stratified.qmd
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/EPIET/IntroCourse_inCop/tree/main
          - text: Report a code issue
            url:  https://github.com/EPIET/IntroCourse_inCop/issues

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: show
    code-summary: "Show the code"
    code-tools: true
    df-print: paged

editor: visual


